data: 
  - '/opt/data/data/driving_log.csv'
  - '/opt/data/data-rev/driving_log.csv'
  - '/opt/data/data-normal1/driving_log.csv'
  - '/opt/data/data-normal-rev1/driving_log.csv'
  - '/opt/data/data-left/driving_log.csv'
  - '/opt/data/data-valid/driving_log.csv'
  
target_image_dir: '/opt/data/'
is_both_side: 0
is_flip: 1
batch_size: 64
epochs: 15

im_size: !!python/tuple [160, 320, 3]
cropping_height: !!python/tuple [70, 20]
cropping_width: !!python/tuple [0, 0]